"""add source, external_id, apply_url to jobs

Revision ID: 42af2f02d74d
Revises: bb7f63ab2d02
Create Date: 2026-08-23 21:50:30.748766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42af2f02d74d'
down_revision: Union[str, Sequence[str], None] = 'bb7f63ab2d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source', sa.String(length=32), nullable=True))
    op.add_column('jobs', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('apply_url', sa.String(length=2048), nullable=True))
    op.create_unique_constraint('uq_jobs_source_external_id', 'jobs', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_source_external_id', 'jobs', type_='unique')
    op.drop_column('jobs', 'apply_url')
    op.drop_column('jobs', 'external_id')
    op.drop_column('jobs', 'source')
    # ### end Alembic commands ###
