"""add learning roadmap tables

Revision ID: d90081e60895
Revises: f0b6054e237f
Create Date: 2026-09-03 15:52:11.604252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90081e60895'
down_revision: Union[str, Sequence[str], None] = 'f0b6054e237f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='learning_path_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_target_role'), 'learning_paths', ['target_role'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_index('uq_learning_paths_user_target_role_active', 'learning_paths', ['user_id', 'target_role'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('skill_learning_resources',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.Enum('COURSE', 'ARTICLE', 'PROJECT', 'DOCS', name='learning_resource_type'), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_learning_resources_skill_id'), 'skill_learning_resources', ['skill_id'], unique=False)
    op.create_table('skill_prerequisites',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('requires_skill_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('skill_id != requires_skill_id', name='ck_skill_prerequisites_no_self_reference'),
    sa.ForeignKeyConstraint(['requires_skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'requires_skill_id', name='uq_skill_prerequisites_skill_requires')
    )
    op.create_index(op.f('ix_skill_prerequisites_requires_skill_id'), 'skill_prerequisites', ['requires_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_prerequisites_skill_id'), 'skill_prerequisites', ['skill_id'], unique=False)
    op.create_table('learning_path_items',
    sa.Column('learning_path_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Enum('FOUNDATIONS', 'CORE', 'ADVANCED', name='roadmap_phase'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learning_path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learning_path_id', 'skill_id', name='uq_learning_path_items_path_skill')
    )
    op.create_index(op.f('ix_learning_path_items_learning_path_id'), 'learning_path_items', ['learning_path_id'], unique=False)
    op.create_index(op.f('ix_learning_path_items_skill_id'), 'learning_path_items', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_path_items_skill_id'), table_name='learning_path_items')
    op.drop_index(op.f('ix_learning_path_items_learning_path_id'), table_name='learning_path_items')
    op.drop_table('learning_path_items')
    op.drop_index(op.f('ix_skill_prerequisites_skill_id'), table_name='skill_prerequisites')
    op.drop_index(op.f('ix_skill_prerequisites_requires_skill_id'), table_name='skill_prerequisites')
    op.drop_table('skill_prerequisites')
    op.drop_index(op.f('ix_skill_learning_resources_skill_id'), table_name='skill_learning_resources')
    op.drop_table('skill_learning_resources')
    op.drop_index('uq_learning_paths_user_target_role_active', table_name='learning_paths', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_target_role'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
    # Not auto-generated: autogenerate's `drop_table` never emits `DROP TYPE` for a Postgres
    # native enum (a real, pre-existing gap in this codebase's other enum-bearing migrations too,
    # e.g. `gap_level` in 202608231851 — found here because this is the first time anyone has
    # actually exercised a downgrade/upgrade cycle for an enum-bearing table). Without these,
    # `CREATE TYPE` in a later `upgrade()` re-run fails with "type already exists" since the type
    # silently outlives the table that used it.
    sa.Enum(name='roadmap_phase').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='learning_resource_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='learning_path_status').drop(op.get_bind(), checkfirst=True)
