"""add interview tables

Revision ID: b084ccc24540
Revises: d90081e60895
Create Date: 2026-09-04 16:18:15.490888

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b084ccc24540'
down_revision: Union[str, Sequence[str], None] = 'd90081e60895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_question_bank',
    sa.Column('mode', sa.Enum('TECHNICAL', 'BEHAVIORAL', 'HR', 'SYSTEM_DESIGN', 'ML', 'DATA_SCIENCE', name='interview_mode'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_question_bank_mode'), 'interview_question_bank', ['mode'], unique=False)
    op.create_table('interviews',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('TECHNICAL', 'BEHAVIORAL', 'HR', 'SYSTEM_DESIGN', 'ML', 'DATA_SCIENCE', name='interview_mode'), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='interview_status'), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('bank_question_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bank_question_id'], ['interview_question_bank.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'order_index', name='uq_interview_questions_interview_order')
    )
    op.create_index(op.f('ix_interview_questions_interview_id'), 'interview_questions', ['interview_id'], unique=False)
    op.create_table('interview_answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('interview_evaluations',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('correctness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('depth_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_evaluations')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_interview_questions_interview_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_interview_question_bank_mode'), table_name='interview_question_bank')
    op.drop_table('interview_question_bank')
    # ### end Alembic commands ###
    # Not auto-generated: autogenerate never emits `DROP TYPE` for a Postgres native enum (see
    # Phase 9's 202609031322 migration for the first time this was found and fixed) — without
    # these, a later `upgrade()` re-run's `CREATE TYPE` fails with "type already exists".
    sa.Enum(name='interview_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='interview_mode').drop(op.get_bind(), checkfirst=True)
