"""add job search/predicted category, skill_demand, salary_data

Revision ID: c3fa23bd0560
Revises: 42af2f02d74d
Create Date: 2026-08-24 15:09:00.832829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fa23bd0560'
down_revision: Union[str, Sequence[str], None] = '42af2f02d74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_data',
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('seniority_level', sa.String(length=64), nullable=True),
    sa.Column('p25', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('p50', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('p75', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_title', 'seniority_level', 'period', name='uq_salary_data_title_seniority_period')
    )
    op.create_index(op.f('ix_salary_data_job_title'), 'salary_data', ['job_title'], unique=False)
    op.create_index(op.f('ix_salary_data_period'), 'salary_data', ['period'], unique=False)
    op.create_table('skill_demand',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'period', name='uq_skill_demand_skill_period')
    )
    op.create_index(op.f('ix_skill_demand_period'), 'skill_demand', ['period'], unique=False)
    op.create_index(op.f('ix_skill_demand_skill_id'), 'skill_demand', ['skill_id'], unique=False)
    op.add_column('jobs', sa.Column('search_category', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('predicted_category', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'predicted_category')
    op.drop_column('jobs', 'search_category')
    op.drop_index(op.f('ix_skill_demand_skill_id'), table_name='skill_demand')
    op.drop_index(op.f('ix_skill_demand_period'), table_name='skill_demand')
    op.drop_table('skill_demand')
    op.drop_index(op.f('ix_salary_data_period'), table_name='salary_data')
    op.drop_index(op.f('ix_salary_data_job_title'), table_name='salary_data')
    op.drop_table('salary_data')
    # ### end Alembic commands ###
