"""add career paths, career path skills, skill gaps, skill seo columns

Revision ID: e91885d06d93
Revises: 275130fd1718
Create Date: 2026-08-23 18:51:56.356104

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91885d06d93'
down_revision: Union[str, Sequence[str], None] = '275130fd1718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('related_job_titles', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_career_paths_embedding_hnsw_cosine', 'career_paths', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_career_paths_slug'), 'career_paths', ['slug'], unique=True)
    op.create_table('career_path_skills',
    sa.Column('career_path_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_path_id', 'skill_id', name='uq_career_path_skills_path_skill')
    )
    op.create_index(op.f('ix_career_path_skills_career_path_id'), 'career_path_skills', ['career_path_id'], unique=False)
    op.create_index(op.f('ix_career_path_skills_skill_id'), 'career_path_skills', ['skill_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('gap_level', sa.Enum('MISSING', 'WEAK', 'ADEQUATE', 'STRONG', name='gap_level'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', 'target_role', name='uq_skill_gaps_user_skill_role')
    )
    op.create_index(op.f('ix_skill_gaps_skill_id'), 'skill_gaps', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_target_role'), 'skill_gaps', ['target_role'], unique=False)
    op.create_index(op.f('ix_skill_gaps_user_id'), 'skill_gaps', ['user_id'], unique=False)
    op.add_column('skills', sa.Column('synonyms', sa.ARRAY(sa.String(length=100)), nullable=True))
    op.add_column('skills', sa.Column('seo_summary', sa.Text(), nullable=True))
    op.add_column('skills', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.create_index('ix_skills_embedding_hnsw_cosine', 'skills', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skills_embedding_hnsw_cosine', table_name='skills', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('skills', 'embedding')
    op.drop_column('skills', 'seo_summary')
    op.drop_column('skills', 'synonyms')
    op.drop_index(op.f('ix_skill_gaps_user_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_target_role'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_skill_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_career_path_skills_skill_id'), table_name='career_path_skills')
    op.drop_index(op.f('ix_career_path_skills_career_path_id'), table_name='career_path_skills')
    op.drop_table('career_path_skills')
    op.drop_index(op.f('ix_career_paths_slug'), table_name='career_paths')
    op.drop_index('ix_career_paths_embedding_hnsw_cosine', table_name='career_paths', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('career_paths')
    # ### end Alembic commands ###
